name: Build and test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            COPY_COMMAND: copy
            LIB_EXTENSION: dll
        #os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, macos-13, windows-2022, windows-2019]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }} -DENABLE_TEST=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} -j 4

    - name: Unit tests
      run: |
        ${{matrix.COPY_COMMAND}} ${{steps.strings.outputs.build-output-dir}}/test/dummyLib/Release/dummyLib.${{matrix.LIB_EXTENSION}} ${{steps.strings.outputs.build-output-dir}}/test/unit/Release/
        ${{steps.strings.outputs.build-output-dir}}/test/unit/Release/unitTest
