name: Build and test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: windows-2022
          #   COPY_COMMAND: copy
          #   DUMMY_LIB_PATH: test/dummyLib/Release/dummyLib.dll
          #   UNIT_TEST_PATH: test/unit/Release/
          - os: ubuntu-22.04
            COPY_COMMAND: cp
            DUMMY_LIB_PATH: test/dummyLib/libdummyLib.so
            UNIT_TEST_PATH: test/unit/
            FFMPEG_TEST_NAME: ffmpegTest
          #- os: macos-12
          #  COPY_COMMAND: cp
          #  DUMMY_LIB_PATH: test/dummyLib/libdummyLib.dylib
          #  UNIT_TEST_PATH: test/unit/
             
        #os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, macos-13, windows-2022, windows-2019]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }} -DENABLE_TEST=ON

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} -j 4 --config Release

    - name: Unit tests
      run: |
        ${{matrix.COPY_COMMAND}} ${{steps.strings.outputs.build-output-dir}}/${{matrix.DUMMY_LIB_PATH}} ${{steps.strings.outputs.build-output-dir}}/${{matrix.UNIT_TEST_PATH}}
        cd ${{steps.strings.outputs.build-output-dir}}/${{matrix.UNIT_TEST_PATH}}
        ./unitTest

    - uses: actions/upload-artifact@master
      with:
        name: ${{matrix.FFMPEG_TEST_NAME}}.zip
        path: ${{steps.strings.outputs.build-output-dir}}/test/ffmpegTest/${{matrix.FFMPEG_TEST_NAME}}

  testffmpeg:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: ffmpegTest.zip

    - name: Unzip ffmpegTest
      run: |
        ls -l
        unzip ffmpegTest.zip

    - name: Download FFmpeg
      run: |
        curl -L "${{ secrets.AZURE_BLOB_ROOT_PATH }}ffmpeg/ffmpeg6.0-ubuntu20.zip${{ secrets.AZURE_BLOB_TOKEN }}" -o ffmpeg6.0-ubuntu20.zip
        curl -L "${{ secrets.AZURE_BLOB_ROOT_PATH }}bitstream-testfiles/TestFile_h264_aac_1s_320x240.mp4${{ secrets.AZURE_BLOB_TOKEN }}" -o TestFile_h264_aac_1s_320x240.mp4
        ls -l
        unzip ffmpeg6.0-ubuntu20.zip

    - name: runffmpegTest
      run: |
        ls -l
        ./ffmpegTest
